#!/bin/sh /etc/rc.common
#
# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#

START=95
STOP=01

USE_PROCD=1
PROCD_DEBUG=1

IFNAME=wlan0
SVC_NAME=wpa_supplicant
PKG_NAME=wpa-supplicant-qcacld
BIN_PATH=/usr/sbin/$SVC_NAME
UCI_CONFIG_PATH=/etc/config/$SVC_NAME
LOG_PATH=/tmp/$SVC_NAME-$IFNAME.log
PID_PATH=/var/run/$SVC_NAME-$IFNAME.pid
CONF_PATH=/var/run/$SVC_NAME-$IFNAME.conf

start_service() {
	if [ -x "${BIN_PATH}" ];then
		if [ -f /var/run/$SVC_NAME-wlan0.conf ];then
			IFNAME=wlan0
			echo "IFNAME is $IFNAME" > /dev/kmsg
			BIN_PATH=/usr/sbin/$SVC_NAME
			UCI_CONFIG_PATH=/etc/config/$SVC_NAME
			LOG_PATH=/tmp/$SVC_NAME-$IFNAME.log
			PID_PATH=/var/run/$SVC_NAME-$IFNAME.pid
			CONF_PATH=/var/run/$SVC_NAME-$IFNAME.conf
			config_load "${SVC_NAME}"
			config_get_bool enable_debug cfg enable_debug 0
			mkdir -p /var/run/wpa_supplicant
			chown wifi:wifi /var/run/wpa_supplicant
			procd_open_instance $PKG_NAME
			procd_set_param command $BIN_PATH -Dnl80211 -i$IFNAME -P $PID_PATH -f $LOG_PATH
			procd_append_param command -dddd

			procd_append_param command -c $CONF_PATH
			procd_set_param file $UCI_CONFIG_PATH
			procd_set_param pidfile $PID_PATH
			procd_set_param stdout 1
			procd_set_param stderr 1
			[ -x /sbin/ujail -a -e /etc/capabilities/wpa_supplicant.json ] && {
				procd_add_jail $PKG_NAME
				procd_set_param user wifi
				procd_set_param group wifi
				procd_set_param capabilities /etc/capabilities/wpa_supplicant.json
				procd_set_param no_new_privs 1
			}
			procd_close_instance
		fi
		if [ -f /var/run/$SVC_NAME-wlan1.conf ];then
			IFNAME=wlan1
			echo "IFNAME is $IFNAME" > /dev/kmsg
			BIN_PATH=/usr/sbin/$SVC_NAME
			UCI_CONFIG_PATH=/etc/config/$SVC_NAME
			LOG_PATH=/tmp/$SVC_NAME-$IFNAME.log
			PID_PATH=/var/run/$SVC_NAME-$IFNAME.pid
			CONF_PATH=/var/run/$SVC_NAME-$IFNAME.conf
			config_load "${SVC_NAME}"
			config_get_bool enable_debug cfg enable_debug 0

			mkdir -p /var/run/wpa_supplicant
			chown wifi:wifi /var/run/wpa_supplicant
			procd_open_instance $PKG_NAME
			procd_set_param command $BIN_PATH -Dnl80211 -i$IFNAME -P $PID_PATH -f $LOG_PATH
			echo "enable debug log (append '-dddd') for $SVC_NAME" > /dev/kmsg
			procd_append_param command -dddd

			procd_append_param command -c $CONF_PATH
			procd_set_param file $UCI_CONFIG_PATH
			procd_set_param pidfile $PID_PATH
			procd_set_param stdout 1
			procd_set_param stderr 1
			[ -x /sbin/ujail -a -e /etc/capabilities/wpa_supplicant.json ] && {
				procd_add_jail $PKG_NAME
				procd_set_param user wifi
				procd_set_param group wifi
				procd_set_param capabilities /etc/capabilities/wpa_supplicant.json
				procd_set_param no_new_privs 1
			}
			procd_close_instance
		fi
	fi
}

stop_service() {
	echo "stop $PKG_NAME" > /dev/kmsg
	local pid

	if [ -e "/var/run/$SVC_NAME-wlan0.pid" ];then
		PID_PATH=/var/run/$SVC_NAME-wlan0.pid
		pid=$(cat $PID_PATH)
		echo "kill $SVC_NAME(pid: $pid)" > /dev/kmsg
		kill $pid &> /dev/null
		rm -rf $PID_PATH &> /dev/null
	fi

	if [ -e "/var/run/$SVC_NAME-wlan1.pid" ];then
		PID_PATH=/var/run/$SVC_NAME-wlan1.pid
		pid=$(cat $PID_PATH)
		echo "kill $SVC_NAME(pid: $pid)" > /dev/kmsg
		kill $pid &> /dev/null
		rm -rf $PID_PATH &> /dev/null
	fi
}

reload_service() {
	echo "reload $PKG_NAME" > /dev/kmsg
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger $SVC_NAME
}

restart() {
	echo "restart $PKG_NAME" > /dev/kmsg
	stop
	start
}
