#!/bin/sh /etc/rc.common
#
# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#

USE_PROCD=1
PROCD_DEBUG=1

IFNAME=wlan0
SVC_NAME=wpa_supplicant
PKG_NAME=wpa-supplicant-qcacld
BIN_PATH=/usr/sbin/$SVC_NAME
UCI_CONFIG_PATH=/etc/config/$SVC_NAME
LOG_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.log
PID_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.pid
CONF_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.conf

start_service() {
	local ifname=$1
	if [ -x "${BIN_PATH}" ];then
		if [ -f /data/vendor/wifi/$SVC_NAME-$ifname.conf ];then
			IFNAME=$ifname
			echo "$PKG_NAME: start on $IFNAME" > /dev/kmsg
			# BIN_PATH - /usr/sbin/wpa_supplicant
			BIN_PATH=/usr/sbin/$SVC_NAME
			# UCI_CONFIG_PATH - /etc/config/wpa_supplicant used to reload wpa_supplicant service if it changed
			UCI_CONFIG_PATH=/etc/config/$SVC_NAME
			PID_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.pid
			# CONF_PATH - config file used to start wpa_supplicant service
			CONF_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.conf

			uci set $SVC_NAME.$IFNAME=interface
			uci commit $SVC_NAME
			config_load "${SVC_NAME}"
			config_get log_level log log_level "debug"
			config_get log_folder_mode log log_folder_mode 0

			if [ "$log_folder_mode" = "1" ];then
				echo "$PKG_NAME: store the log in /data/vendor/wifi/ folder" > /dev/kmsg
				LOG_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.log
			fi

			# make the ctrl_interface file as wifi user Id and group Id
			mkdir -p /data/vendor/wifi/wpa_supplicant
			chown wifi:wifi /data/vendor/wifi/wpa_supplicant

			# create a instance to start wpa_supplicant service
			procd_open_instance $IFNAME
			# start wpa_supplicant as the command /usr/sbin/wpa_supplicant -Dnl80211 -i ifname
			# -p /var/run/wpa_supplicant-ifname.pid -f /var/run/wpa_supplicant-ifname.log
			if [ "$log_folder_mode" = "0" ];then
				procd_set_param command $BIN_PATH -Dnl80211 -i$IFNAME -P $PID_PATH
			else
				procd_set_param command $BIN_PATH -Dnl80211 -i$IFNAME -P $PID_PATH -f $LOG_PATH
			fi
			# set log print level
			if [ "$log_level" = "debug" ];then
				procd_append_param command -d
			elif [ "$log_level" = "info" ];then
				echo "$PKG_NAME: log_level is $log_level, unnecessary to do any change" > /dev/kmsg
			else
				echo "$PKG_NAME: unrecognized log level $log_level, set default log level debug" > /dev/kmsg
				procd_append_param command -dddd
			fi

			# set the config file
			procd_append_param command -c $CONF_PATH
			# trigger wpa_supplicant re-start if the config file changed
			procd_set_param file $UCI_CONFIG_PATH
			# set the PID file
			procd_set_param pidfile $PID_PATH
			# set the log print level in procd
			procd_set_param stdout 1
			procd_set_param stderr 1
			[ -x /sbin/ujail -a -e /etc/capabilities/wpa_supplicant.json ] && {
				procd_add_jail $IFNAME
				# wpa_supplicant service will start as the user and group permission
				procd_set_param user wifi
				procd_set_param group wifi
				# wpa_supplicant service's capabilities get from this file
				procd_set_param capabilities /etc/capabilities/wpa_supplicant.json
				procd_set_param no_new_privs 1
			}
			# close the instance after wpa_supplicant service start, free the memory
			procd_close_instance
		fi
	fi
}

stop_service() {
	# procd will invoke service_handle_delete() to kill
	# the instance by default when called stop_service,
	# but it needs send correct instance when create in
	# start_service(). I,e, if the instance create in
	# start_service() is wlan0, it needs send wlan0 when
        # stop.
	echo "$PKG_NAME: stop $1 $2" > /dev/kmsg
	if [ ! -z "$1" ]; then
		echo "$PKG_NAME: delete $SVC_NAME.$1" > /dev/kmsg
		uci delete $SVC_NAME.$1
		uci commit $SVC_NAME
	fi
}

reload_service() {
	echo "$PKG_NAME: reload" > /dev/kmsg
	stop $@
	start $@
}

service_add_interface_trigger() {
	local ifname=$1
	local basescript=$(readlink "$initscript")
	local name="$(basename ${basescript:-$initscript})"

	echo "$PKG_NAME: add interface trigger for $ifname" > /dev/kmsg
	procd_add_interface_trigger "interface.down" $ifname /etc/init.d/$name stop $ifname ifdown
}

service_triggers() {
	echo "$PKG_NAME: triggers" > /dev/kmsg
	procd_add_reload_trigger $SVC_NAME
	config_load "${SVC_NAME}"
	config_foreach service_add_interface_trigger interface
}

restart() {
	echo "$PKG_NAME: restart" > /dev/kmsg
	stop $@
	start $@
}
