#!/bin/sh /etc/rc.common
#
# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#

USE_PROCD=1
PROCD_DEBUG=1

IFNAME=wlan0
SVC_NAME=wpa_supplicant
PKG_NAME=wpa-supplicant-qcacld
BIN_PATH=/usr/sbin/$SVC_NAME
UCI_CONFIG_PATH=/etc/config/$SVC_NAME
LOG_PATH=/tmp/$SVC_NAME-$IFNAME.log
PID_PATH=/var/run/$SVC_NAME-$IFNAME.pid
CONF_PATH=/var/run/$SVC_NAME-$IFNAME.conf

start_service() {
	local ifname=$1
	if [ -x "${BIN_PATH}" ];then
		if [ -f /var/run/$SVC_NAME-$ifname.conf ];then
			IFNAME=$ifname
			echo "IFNAME is $IFNAME" > /dev/kmsg
			# BIN_PATH - /usr/sbin/wpa_supplicant
			BIN_PATH=/usr/sbin/$SVC_NAME
			# UCI_CONFIG_PATH - /etc/config/wpa_supplicant used to reload wpa_supplicant service if it changed
			UCI_CONFIG_PATH=/etc/config/$SVC_NAME
			# LOG_PATH - /tmp/wpa_supplicant-ifname.log used to catch wpa_supplicant log
			LOG_PATH=/tmp/$SVC_NAME-$IFNAME.log
			PID_PATH=/var/run/$SVC_NAME-$IFNAME.pid
			# CONF_PATH - config file used to start wpa_supplicant service
			CONF_PATH=/var/run/$SVC_NAME-$IFNAME.conf

			config_load "${SVC_NAME}"
			config_get_bool enable_debug cfg enable_debug 0

			# make the ctrl_interface file as wifi user Id and group Id
			mkdir -p /var/run/wpa_supplicant
			chown wifi:wifi /var/run/wpa_supplicant

			# create a instance to start wpa_supplicant service
			procd_open_instance $IFNAME
			# start hostapd as the command /usr/sbin/wpa_supplicant -Dnl80211 -i ifname
			# -p /var/run/wpa_supplicant-ifname.pid -f /var/run/wpa_supplicant-ifname.log
			procd_set_param command $BIN_PATH -Dnl80211 -i$IFNAME -P $PID_PATH -f $LOG_PATH
			# give the highest the debug log level to dump more log
			procd_append_param command -dddd

			# set the config file
			procd_append_param command -c $CONF_PATH
			# trigger wpa_supplicant re-start if the config file changed
			procd_set_param file $UCI_CONFIG_PATH
			# set the PID file
			procd_set_param pidfile $PID_PATH
			# set the log print level in procd
			procd_set_param stdout 1
			procd_set_param stderr 1
			[ -x /sbin/ujail -a -e /etc/capabilities/wpa_supplicant.json ] && {
				procd_add_jail $IFNAME
				# wpa_supplicant service will start as the user and group permission
				procd_set_param user wifi
				procd_set_param group wifi
				# wpa_supplicant service's capabilities get from this file
				procd_set_param capabilities /etc/capabilities/wpa_supplicant.json
				procd_set_param no_new_privs 1
			}
			# close the instance after wpa_supplicant service start, free the memory
			procd_close_instance
		fi
	fi
}

stop_service() {
	# procd will invoke service_handle_delete() to kill
	# the instance by default when called stop_service,
	# but it needs send correct instance when create in
	# start_service(). I,e, if the instance create in
	# start_service() is wlan0, it needs send wlan0 when
        # stop.
	echo "stop $1" > /dev/kmsg
}

reload_service() {
	echo "reload $PKG_NAME" > /dev/kmsg
	stop $@
	start $@
}

service_triggers() {
	procd_add_reload_trigger $SVC_NAME
}

restart() {
	echo "restart $PKG_NAME" > /dev/kmsg
	stop $@
	start $@
}
