BBFILES += "${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend "
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-wlan"
BBFILE_PRIORITY_qti-wlan = "12"
BBFILE_PATTERN_qti-wlan := "^${LAYERDIR}/"

LAYERDEPENDS_qti-wlan = ""
LAYERSERIES_COMPAT_qti-wlan = "dunfell kirkstone"
