#Conf file to load wlan-driver modules at boot-up time
#Install under /etc/modules-load-d/ path
#Load WLAN platform modules first in correct order
cnss_prealloc
cnss_utils
cnss_nl
cnss_plat_ipc_qmi_svc
wlan_firmware_service
cnss2
#Load WLAN driver module last
qca_cld3_peach_v2