#! /bin/sh

#Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

export MODULE_BASE=/lib/modules
set -e

case "$1" in
  start)
        echo -n "Starting/Loading wlan cnss modules: "

	fullpath=$(find $MODULE_BASE -name cnss2.ko)
	if [ -z "$fullpath" ]; then
		echo -n "wlan cnss modules missing "
		exit 0
	fi

	basepath=$(dirname $fullpath)

        echo "wlan cnss:start/load" > /dev/kmsg
	if [ -f $basepath/cnss_utils.ko ]; then
		insmod $basepath/cnss_utils.ko
	fi
	if [ -f $basepath/cnss_nl.ko ]; then
		insmod $basepath/cnss_nl.ko
	fi

	if [ $(cat /sys/firmware/devicetree/base/model | grep -c ROME) = 1 ];then

		if [ -f $basepath/cnss_crypto.ko ]; then
			insmod $basepath/cnss_crypto.ko
		fi
		if [ -f $basepath/logger.ko ]; then
			insmod $basepath/logger.ko
		fi
		if [ -f $basepath/cnss.ko ]; then
			insmod $basepath/cnss.ko
		fi
	else
		if [ -f $basepath/cnss_plat_ipc_qmi_svc.ko ]; then
			insmod $basepath/cnss_plat_ipc_qmi_svc.ko
		fi
		if [ -f $basepath/wlan_firmware_service.ko ]; then
			insmod $basepath/wlan_firmware_service.ko
		fi
		if [ -f $basepath/cnss_prealloc.ko ]; then
			insmod $basepath/cnss_prealloc.ko
		fi
		if [ -f $basepath/cnss2.ko ]; then
			insmod $basepath/cnss2.ko
		fi
	fi
        echo "done loading wlan cnss modules"

        if [ $(cat /tmp/sysinfo/board_name | grep -c sdxkova) = 1 ]; then
                chmod 0664 /etc/misc/wifi/WCNSS_qcom_cfg.ini
        fi
        ;;
  stop)
        echo -n "Bypassing unloading of wlan modules"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
