#! /bin/sh

#Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

export MODULE_BASE=/lib/modules
set -e

case "$1" in
  start)
        echo -n "Starting/Loading wlan cnss modules: "

	bus_type_path="/etc/misc/wifi/wlan_bus_type"
	fullpath=$(find $MODULE_BASE -name cnss2.ko)
	if [ -z "$fullpath" ]; then
		echo -n "wlan cnss modules missing "
		exit 0
	fi

	basepath=$(dirname $fullpath)

        echo "wlan cnss:start/load" > /dev/kmsg
	if [ -f $basepath/cnss_utils.ko ]; then
		insmod $basepath/cnss_utils.ko
	fi
	if [ -f $basepath/cnss_nl.ko ]; then
		insmod $basepath/cnss_nl.ko
	fi

	dev_type="HSP"
	if [ $(cat /sys/firmware/devicetree/base/model | grep -c ROME) = 1 ];then
		dev_type="ROME"
	fi

	bus_type="PCIe"
	if [ -f "${bus_type_path}" ] && [ $(cat "${bus_type_path}" | grep -ic SDIO) = 1 ];then
		bus_type="SDIO"
	fi

	type_comb="${dev_type}_${bus_type}"
	case "${type_comb}" in
	"ROME_PCIe")
		if [ -f $basepath/cnss_crypto.ko ]; then
			insmod $basepath/cnss_crypto.ko
		fi
		if [ -f $basepath/logger.ko ]; then
			insmod $basepath/logger.ko
		fi
		if [ -f $basepath/cnss.ko ]; then
			insmod $basepath/cnss.ko
		fi
		if [ -f $basepath/wlan_prealloc.ko ] && [ ! -d /sys/module/wlan_prealloc ]; then
			insmod $basepath/wlan_prealloc.ko
		fi
		;;
	"ROME_SDIO")
		if [ -f $basepath/cnss_crypto.ko ]; then
			insmod $basepath/cnss_crypto.ko
		fi
		if [ -f $basepath/cnss_sdio_bus.ko ]; then
			insmod $basepath/cnss_sdio_bus.ko
		fi
		if [ -f $basepath/wlan_prealloc.ko ] && [ ! -d /sys/module/wlan_prealloc ]; then
			insmod $basepath/wlan_prealloc.ko
		fi
		;;
	*)
		if [ -f $basepath/cnss_plat_ipc_qmi_svc.ko ]; then
			insmod $basepath/cnss_plat_ipc_qmi_svc.ko
		fi
		if [ -f $basepath/wlan_firmware_service.ko ]; then
			insmod $basepath/wlan_firmware_service.ko
		fi
		if [ -f $basepath/cnss_prealloc.ko ]; then
			insmod $basepath/cnss_prealloc.ko
		fi
		if [ -f $basepath/cnss2.ko ]; then
			insmod $basepath/cnss2.ko
		fi
		;;
	esac
        echo "done loading wlan cnss modules"
        ;;
  stop)
        echo -n "Bypassing unloading of wlan modules"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
