#!/bin/sh /etc/rc.common
#
# Copyright (c) 2023-2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#

. /lib/wifi/qcacld32-utils.sh

USE_PROCD=1
PROCD_DEBUG=1

PKG_NAME=hostapd-global
WPAD_VARRUN="$(get_wlan_module_path)"

BOOT_KPI_NODE_DEFAULT=/sys/kernel/debug/bootkpi/kpi_values
BOOT_KPI_NODE_5_4=/sys/kernel/boot_kpi/kpi_values

add_boot_kpi_marker() {
	local major=`uname -r | awk -F . '{print $1}'`
	local minor=`uname -r | awk -F . '{print $2}'`
	local boot_kpi_node=$BOOT_KPI_NODE_DEFAULT
	local boot_kpi_marker="M - $1 - enable beaconing"

	# compare kernel version with 5.4
	if [ "$major" -gt "5" ] || [ "$major" -eq "5" -a "$minor" -ge "4" ]; then
		boot_kpi_node=$BOOT_KPI_NODE_5_4
	fi

	# Only add maker for the 1st SAP after device bootup
	cat "$boot_kpi_node" | grep "$boot_kpi_marker" 2>&1 > /dev/null
	if [ $? -eq 0 ]; then
		return
	fi

	echo -n $boot_kpi_marker >> $boot_kpi_node
}

start_service() {
	echo "$PKG_NAME: start" > /dev/kmsg
	add_boot_kpi_marker $PKG_NAME
	procd_open_instance $PKG_NAME
	procd_set_param command /usr/sbin/hostapd -g $WPAD_VARRUN/hostapd-global -B -P $WPAD_VARRUN/hostapd-global.pid
	procd_set_param stdout 1
	procd_set_param stderr 1

	# Debug start
	config_load hostapd
	config_get log_level log log_level "info"
	config_get log_folder_mode log log_folder_mode 0
	case "$log_level" in
		excessive)
			procd_append_param command -ddd
		;;
		dump)
			procd_append_param command -dd
		;;
		debug)
			procd_append_param command -d
		;;
		warning)
			procd_append_param command -q
		;;
		error)
			procd_append_param command -qq
		;;
		*)
		;;
	esac
	[ "$log_folder_mode" = "1" ] && procd_append_param command -f $WPAD_VARRUN/hostapd-global.log
	# Debug end

	[ -x /sbin/ujail -a -e /etc/capabilities/hostapd-daemon.json ] && {
		if [ ! -d $WPAD_VARRUN ]; then
			mkdir -p $WPAD_VARRUN
		fi
		chown ":wifi" $WPAD_VARRUN
		chmod 777 $WPAD_VARRUN
		procd_add_jail $PKG_NAME
		procd_set_param user wifi
		procd_set_param group wifi
		procd_set_param capabilities /etc/capabilities/hostapd-daemon.json
	}
	procd_close_instance
}

stop_service() {
	echo "$PKG_NAME: stop" > /dev/kmsg
	if  [ -e $WPAD_VARRUN/hostapd-global.pid ]
	then
		chmod 666 $WPAD_VARRUN/hostapd-global.pid
		kill $(cat $WPAD_VARRUN/hostapd-global.pid) &> /dev/null
		rm $WPAD_VARRUN/hostapd-global.pid &> /dev/null
	fi
}

reload_service() {
	echo "$PKG_NAME: reload" > /dev/kmsg
	stop
	start
}

restart() {
	echo "$PKG_NAME: restart" > /dev/kmsg
	stop
	start
}
