#!/bin/sh /etc/rc.common
#
# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#

USE_PROCD=1
PROCD_DEBUG=1

IFNAME=wlan0
SVC_NAME=hostapd
PKG_NAME=hostapd-daemon
BIN_PATH=/usr/sbin/$SVC_NAME
UCI_CONFIG_PATH=/etc/config/$SVC_NAME
LOG_PATH=/tmp/$SVC_NAME-$IFNAME.log
PID_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.pid
CONF_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.conf

start_service() {
	local ifname=$1
	if [ -x "${BIN_PATH}" ];then
		if [ -f /data/vendor/wifi/$SVC_NAME-$ifname.conf ];then
			IFNAME=$ifname
			echo "IFNAME is $IFNAME" > /dev/kmsg
			# BIN_PATH - /usr/sbin/hostapd
			BIN_PATH=/usr/sbin/$SVC_NAME
			# UCI_CONFIG_PATH - /etc/config/hostapd used to reload hostapd service if it changed
			UCI_CONFIG_PATH=/etc/config/$SVC_NAME
			PID_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.pid
			# CONF_PATH - config file used to start hostapd service
			CONF_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.conf

			config_load "${SVC_NAME}"
			config_get log_level log log_level "debug"
			config_get log_folder_mode log log_folder_mode 0

			if [ "$log_folder_mode" = "1" ];then
				echo "store log in /tmp/$SVC_NAME-$IFNAME.log"
				LOG_PATH=/tmp/$SVC_NAME-$IFNAME.log
			elif [ "$log_folder_mode" = "2" ];then
				echo "store log in /data/vendor/wifi/$SVC_NAME-$IFNAME.log"
				LOG_PATH=/data/vendor/wifi/$SVC_NAME-$IFNAME.log
			fi

			# make the ctrl_interface file as wifi user Id and group Id
			mkdir -p /data/vendor/wifi/hostapd
			chown wifi:wifi /data/vendor/wifi/hostapd

			# create a instance to start hostapd service
			procd_open_instance $IFNAME
			# start hostapd as the command /usr/sbin/hostapd -p /var/run/hostapd-ifname.pid -f /var/run/hostapd-ifname.log
			if [ "$log_folder_mode" = "0" ];then
				procd_set_param command $BIN_PATH -P $PID_PATH
			else
				procd_set_param command $BIN_PATH -P $PID_PATH -f $LOG_PATH
			fi
			# set log print level
			if [ "$log_level" = "debug" ];then
				procd_append_param command -d
			elif [ "$log_level" = "info" ];then
				echo "log_level is $log_level, unnecessary to do any change"
			else
				echo "unrecognized log level $log_level, set default log level debug"
				procd_append_param command -dddd
			fi

			# set the config file
			procd_append_param command $CONF_PATH
			# trigger hostapd re-start if the config file changed
			procd_set_param file $UCI_CONFIG_PATH
			# set the PID file
			procd_set_param pidfile $PID_PATH
			# set the log print level in procd
			procd_set_param stdout 1
			procd_set_param stderr 1
			# set hostapd service's necessary capabilities to start
			[ -x /sbin/ujail -a -e /etc/capabilities/hostapd-daemon.json ] && {
				procd_add_jail $IFNAME
				# hostapd service will start as the user and group permission
				procd_set_param user wifi
				procd_set_param group wifi
				# hostapd service's capabilities get from this file
				procd_set_param capabilities /etc/capabilities/hostapd-daemon.json
				procd_set_param no_new_privs 1
			}
			# close the instance after hostapd service start, free the memory
			procd_close_instance
		fi
	fi
}

stop_service() {
	# procd will invoke service_handle_delete() to kill
	# the instance created when service start by default.
	# i.e, if the instance name is wlan0, the instance
        # sent to stop_service() should keep the same.
	echo "stop $1" > /dev/kmsg
}

reload_service() {
	echo "reload $PKG_NAME" > /dev/kmsg
	stop $@
	start $@
}

service_triggers() {
	procd_add_reload_trigger $SVC_NAME
}

restart() {
	echo "restart $PKG_NAME" > /dev/kmsg
	stop $@
	start $@
}
